### ISSUE TITLE
spawn raspistill ENOENT

### ISSUE THREAD

**Issue by ayontulip** [arvindr21/pi_livestreaming#2]
node index.js
listening on *:3000
Total clients connected :  1
Total clients connected :  2
Total clients connected :  3
Watching for changes...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn raspistill ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)

**Comment by datomnurdin** [comment]
I'm also got this kind of error message. Anyone?

**Comment by ImValox** [comment]
Me too
